"use strict";

const argentineProvinces = new Map([
  ["B", "Buenos Aires"],
  ["K", "Catamarca"],
  ["H", "Chaco"],
  ["U", "Chubut"],
  ["C", "Ciudad Autónoma de Buenos Aires"],
  ["W", "Corrientes"],
  ["X", "Córdoba"],
  ["E", "Entre Ríos"],
  ["P", "Formosa"],
  ["Y", "Jujuy"],
  ["L", "La Pampa"],
  ["F", "La Rioja"],
  ["M", "Mendoza"],
  ["N", "Misiones"],
  ["Q", "Neuquén"],
  ["R", "Río Negro"],
  ["A", "Salta"],
  ["J", "San Juan"],
  ["D", "San Luis"],
  ["Z", "Santa Cruz"],
  ["S", "Santa Fe"],
  ["G", "Santiago del Estero"],
  ["V", "Tierra del Fuego"],
  ["T", "Tucumán"],
]);

const australianStates = new Map([
  ["ACT", "Australian Capital Territory"],
  ["NSW", "New South Wales"],
  ["NT", "Northern Territory"],
  ["QLD", "Queensland"],
  ["SA", "South Australia"],
  ["TAS", "Tasmania"],
  ["VIC", "Victoria"],
  ["WA", "Western Australia"],
]);

const austrianStates = new Map([
  ["AT-1", "Burgenland"],
  ["AT-2", "Kärnten"],
  ["AT-3", "Niederösterreich"],
  ["AT-4", "Oberösterreich"],
  ["AT-5", "Salzburg"],
  ["AT-6", "Steiermark"],
  ["AT-7", "Tirol"],
  ["AT-8", "Vorarlberg"],
  ["AT-9", "Wien"],
]);

const bahamianDistricts = new Map([
  ["BS-AK", "Acklins"],
  ["BS-BY", "Berry Islands"],
  ["BS-BI", "Bimini"],
  ["BS-BP", "Black Point"],
  ["BS-CI", "Cat Island"],
  ["BS-CO", "Central Abaco"],
  ["BS-CS", "Central Andros"],
  ["BS-CE", "Central Eleuthera"],
  ["BS-FP", "City of Freeport"],
  ["BS-CK", "Crooked Island and Long Cay"],
  ["BS-EG", "East Grand Bahama"],
  ["BS-EX", "Exuma"],
  ["BS-GC", "Grand Cay"],
  ["BS-HI", "Harbour Island"],
  ["BS-HT", "Hope Town"],
  ["BS-IN", "Inagua"],
  ["BS-LI", "Long Island"],
  ["BS-MC", "Mangrove Cay"],
  ["BS-MG", "Mayaguana"],
  ["BS-MI", "Moore's Island"],
  ["BS-NO", "North Abaco"],
  ["BS-NS", "North Andros"],
  ["BS-NE", "North Eleuthera"],
  ["BS-RI", "Ragged Island"],
  ["BS-RC", "Rum Cay"],
  ["BS-SS", "San Salvador"],
  ["BS-SO", "South Abaco"],
  ["BS-SA", "South Andros"],
  ["BS-SE", "South Eleuthera"],
  ["BS-SW", "Spanish Wells"],
  ["BS-WG", "West Grand Bahama"],
]);

const barbadianParishes = new Map([
  ["BB-01", "Christ Church"],
  ["BB-02", "Saint Andrew"],
  ["BB-03", "Saint George"],
  ["BB-04", "Saint James"],
  ["BB-05", "Saint John"],
  ["BB-06", "Saint Joseph"],
  ["BB-07", "Saint Lucy"],
  ["BB-08", "Saint Michael"],
  ["BB-09", "Saint Peter"],
  ["BB-10", "Saint Philip"],
  ["BB-11", "Saint Thomas"],
]);

const belarusianOblasts = new Map([
  ["BY-BR", "Brestskaja oblast'"],
  ["BY-BR", "Brestskaya oblast'"],
  ["BY-HO", "Gomel'skaja oblast'"],
  ["BY-HO", "Gomel'skaya oblast'"],
  ["BY-HR", "Grodnenskaja oblast'"],
  ["BY-HR", "Grodnenskaya oblast'"],
  ["BY-MI", "Minskaja oblast'"],
  ["BY-MI", "Minskaya oblast'"],
  ["BY-MA", "Mogilevskaja oblast'"],
  ["BY-MA", "Mogilevskaya oblast'"],
  ["BY-VI", "Vitebskaja oblast'"],
  ["BY-VI", "Vitebskaya oblast'"],
]);

const brazilianStates = new Map([
  ["AC", "Acre"],
  ["AL", "Alagoas"],
  ["AP", "Amapá"],
  ["AM", "Amazonas"],
  ["BA", "Bahia"],
  ["CE", "Ceará"],
  ["DF", "Distrito Federal"],
  ["ES", "Espírito Santo"],
  ["GO", "Goiás"],
  ["MA", "Maranhão"],
  ["MT", "Mato Grosso"],
  ["MS", "Mato Grosso do Sul"],
  ["MG", "Minas Gerais"],
  ["PR", "Paraná"],
  ["PB", "Paraíba"],
  ["PA", "Pará"],
  ["PE", "Pernambuco"],
  ["PI", "Piauí"],
  ["RN", "Rio Grande do Norte"],
  ["RS", "Rio Grande do Sul"],
  ["RJ", "Rio de Janeiro"],
  ["RO", "Rondônia"],
  ["RR", "Roraima"],
  ["SC", "Santa Catarina"],
  ["SE", "Sergipe"],
  ["SP", "São Paulo"],
  ["TO", "Tocantins"],
]);

const canadianProvinces = new Map([
  ["AB", "Alberta"],
  ["BC", "British Columbia"],
  ["MB", "Manitoba"],
  ["NB", "New Brunswick"],
  ["NL", "Newfoundland and Labrador"],
  ["NT", "Northwest Territories"],
  ["NS", "Nova Scotia"],
  ["NU", "Nunavut"],
  ["ON", "Ontario"],
  ["PE", "Prince Edward Island"],
  ["QC", "Quebec"],
  ["SK", "Saskatchewan"],
  ["YT", "Yukon Territory"],
]);

const capeVerdeanMunicipalities = new Map([
  ["CV-BV", "Boa Vista"],
  ["CV-BR", "Brava"],
  ["CV-MA", "Maio"],
  ["CV-MO", "Mosteiros"],
  ["CV-PA", "Paul"],
  ["CV-PN", "Porto Novo"],
  ["CV-PR", "Praia"],
  ["CV-RB", "Ribeira Brava"],
  ["CV-RG", "Ribeira Grande"],
  ["CV-RS", "Ribeira Grande de Santiago"],
  ["CV-SL", "Sal"],
  ["CV-CA", "Santa Catarina"],
  ["CV-CF", "Santa Catarina do Fogo"],
  ["CV-CR", "Santa Cruz"],
  ["CV-SD", "São Domingos"],
  ["CV-SF", "São Filipe"],
  ["CV-SO", "São Lourenço dos Órgãos"],
  ["CV-SM", "São Miguel"],
  ["CV-SS", "São Salvador do Mundo"],
  ["CV-SV", "São Vicente"],
  ["CV-TA", "Tarrafal"],
  ["CV-TS", "Tarrafal de São Nicolau"],
]);

const chileanRegions = new Map([
  ["AI", "Aysén"],
  ["AN", "Antofagasta"],
  ["AP", "Arica y Parinacota"],
  ["AT", "Atacama"],
  ["BI", "Biobío"],
  ["CO", "Coquimbo"],
  ["AR", "La Araucanía"],
  ["LI", "Libertador General Bernardo O'Higgins"],
  ["LL", "Los Lagos"],
  ["LR", "Los Ríos"],
  ["MA", "Magallanes"],
  ["ML", "Maule"],
  ["RM", "Región Metropolitana de Santiago"],
  ["TA", "Tarapacá"],
  ["VS", "Valparaíso"],
  ["NB", "Ñuble"],
]);

const chineseProvinces = new Map([
  ["AH", "Anhui"],
  ["BJ", "Beijing"],
  ["CQ", "Chongqing"],
  ["FJ", "Fujian"],
  ["GS", "Gansu"],
  ["GD", "Guangdong"],
  ["GX", "Guangxi"],
  ["GZ", "Guizhou"],
  ["HI", "Hainan"],
  ["HE", "Hebei"],
  ["HL", "Heilongjiang"],
  ["HA", "Henan"],
  ["HB", "Hubei"],
  ["HN", "Hunan"],
  ["NM", "Inner Mongolia"],
  ["JS", "Jiangsu"],
  ["JX", "Jiangxi"],
  ["JL", "Jilin"],
  ["LN", "Liaoning"],
  ["NX", "Ningxia"],
  ["QH", "Qinghai"],
  ["SN", "Shaanxi"],
  ["SD", "Shandong"],
  ["SH", "Shanghai"],
  ["SX", "Shanxi"],
  ["SC", "Sichuan"],
  ["TJ", "Tianjin"],
  ["YZ", "Tibet"],
  ["XJ", "Xinjiang"],
  ["YN", "Yunnan"],
  ["ZJ", "Zhejiang"],
]);

const columbianDepartments = new Map([
  ["AMA", "Amazonas"],
  ["ANT", "Antioquia"],
  ["ARA", "Arauca"],
  ["ATL", "Atlántico"],
  ["BOL", "Bolívar"],
  ["BOY", "Boyacá"],
  ["CAL", "Caldas"],
  ["CAQ", "Caquetá"],
  ["CAS", "Casanare"],
  ["CAU", "Cauca"],
  ["CES", "Cesar"],
  ["CHO", "Chocó"],
  ["CUN", "Cundinamarca"],
  ["COR", "Córdoba"],
  ["DC", "Distrito Capital de Bogotá"],
  ["GUA", "Guainía"],
  ["GUV", "Guaviare"],
  ["HUI", "Huila"],
  ["LAG", "La Guajira"],
  ["MAG", "Magdalena"],
  ["MET", "Meta"],
  ["NAR", "Nariño"],
  ["NSA", "Norte de Santander"],
  ["PUT", "Putumayo"],
  ["QUI", "Quindío"],
  ["RIS", "Risaralda"],
  ["SAP", "San Andrés, Providencia y Santa Catalina"],
  ["SAN", "Santander"],
  ["SUC", "Sucre"],
  ["TOL", "Tolima"],
  ["VAC", "Valle del Cauca"],
  ["VAU", "Vaupés"],
  ["VID", "Vichada"],
]);

const costaRicanProvinces = new Map([
  ["CR-A", "Alajuela"],
  ["CR-C", "Cartago"],
  ["CR-G", "Guanacaste"],
  ["CR-H", "Heredia"],
  ["CR-L", "Limón"],
  ["CR-P", "Puntarenas"],
  ["CR-SJ", "San José"],
]);

const countries = new Map([
  ["AF", "Afghanistan"],
  ["AX", "Åland Islands"],
  ["AL", "Albania"],
  ["DZ", "Algeria"],
  ["AD", "Andorra"],
  ["AO", "Angola"],
  ["AI", "Anguilla"],
  ["AG", "Antigua & Barbuda"],
  ["AR", "Argentina"],
  ["AM", "Armenia"],
  ["AW", "Aruba"],
  ["AC", "Ascension Island"],
  ["AU", "Australia"],
  ["AT", "Austria"],
  ["AZ", "Azerbaijan"],
  ["BS", "Bahamas"],
  ["BH", "Bahrain"],
  ["BD", "Bangladesh"],
  ["BB", "Barbados"],
  ["BY", "Belarus"],
  ["BE", "Belgium"],
  ["BZ", "Belize"],
  ["BJ", "Benin"],
  ["BM", "Bermuda"],
  ["BT", "Bhutan"],
  ["BO", "Bolivia"],
  ["BA", "Bosnia & Herzegovina"],
  ["BW", "Botswana"],
  ["BR", "Brazil"],
  ["IO", "British Indian Ocean Territory"],
  ["VG", "British Virgin Islands"],
  ["BN", "Brunei"],
  ["BG", "Bulgaria"],
  ["BF", "Burkina Faso"],
  ["BI", "Burundi"],
  ["KH", "Cambodia"],
  ["CM", "Cameroon"],
  ["CA", "Canada"],
  ["CV", "Cape Verde"],
  ["BQ", "Caribbean Netherlands"],
  ["KY", "Cayman Islands"],
  ["CF", "Central African Republic"],
  ["TD", "Chad"],
  ["CL", "Chile"],
  ["CN", "China"],
  ["CX", "Christmas Island"],
  ["CC", "Cocos (Keeling) Islands"],
  ["CO", "Colombia"],
  ["KM", "Comoros"],
  ["CG", "Congo - Brazzaville"],
  ["CD", "Congo - Kinshasa"],
  ["CK", "Cook Islands"],
  ["CR", "Costa Rica"],
  ["HR", "Croatia"],
  ["CW", "Curaçao"],
  ["CY", "Cyprus"],
  ["CZ", "Czechia"],
  ["CI", "Côte d'Ivoire"],
  ["DK", "Denmark"],
  ["DJ", "Djibouti"],
  ["DM", "Dominica"],
  ["DO", "Dominican Republic"],
  ["EC", "Ecuador"],
  ["EG", "Egypt"],
  ["SV", "El Salvador"],
  ["GQ", "Equatorial Guinea"],
  ["ER", "Eritrea"],
  ["EE", "Estonia"],
  ["SZ", "Eswatini"],
  ["ET", "Ethiopia"],
  ["FK", "Falkland Islands"],
  ["FO", "Faroe Islands"],
  ["FJ", "Fiji"],
  ["FI", "Finland"],
  ["FR", "France"],
  ["GF", "French Guiana"],
  ["PF", "French Polynesia"],
  ["TF", "French Southern Territories"],
  ["GA", "Gabon"],
  ["GM", "Gambia"],
  ["GE", "Georgia"],
  ["DE", "Germany"],
  ["GH", "Ghana"],
  ["GI", "Gibraltar"],
  ["GR", "Greece"],
  ["GL", "Greenland"],
  ["GD", "Grenada"],
  ["GP", "Guadeloupe"],
  ["GT", "Guatemala"],
  ["GG", "Guernsey"],
  ["GN", "Guinea"],
  ["GW", "Guinea-Bissau"],
  ["GY", "Guyana"],
  ["HT", "Haiti"],
  ["HN", "Honduras"],
  ["HK", "Hong Kong SAR"],
  ["HU", "Hungary"],
  ["IS", "Iceland"],
  ["IN", "India"],
  ["ID", "Indonesia"],
  ["IQ", "Iraq"],
  ["IE", "Ireland"],
  ["IM", "Isle of Man"],
  ["IL", "Israel"],
  ["IT", "Italy"],
  ["JM", "Jamaica"],
  ["JP", "Japan"],
  ["JE", "Jersey"],
  ["JO", "Jordan"],
  ["KZ", "Kazakhstan"],
  ["KE", "Kenya"],
  ["KI", "Kiribati"],
  ["XK", "Kosovo"],
  ["KW", "Kuwait"],
  ["KG", "Kyrgyzstan"],
  ["LA", "Laos"],
  ["LV", "Latvia"],
  ["LB", "Lebanon"],
  ["LS", "Lesotho"],
  ["LR", "Liberia"],
  ["LY", "Libya"],
  ["LI", "Liechtenstein"],
  ["LT", "Lithuania"],
  ["LU", "Luxembourg"],
  ["MO", "Macao SAR"],
  ["MG", "Madagascar"],
  ["MW", "Malawi"],
  ["MY", "Malaysia"],
  ["MV", "Maldives"],
  ["ML", "Mali"],
  ["MT", "Malta"],
  ["MQ", "Martinique"],
  ["MR", "Mauritania"],
  ["MU", "Mauritius"],
  ["YT", "Mayotte"],
  ["MX", "Mexico"],
  ["MD", "Moldova"],
  ["MC", "Monaco"],
  ["MN", "Mongolia"],
  ["ME", "Montenegro"],
  ["MS", "Montserrat"],
  ["MA", "Morocco"],
  ["MZ", "Mozambique"],
  ["MM", "Myanmar (Burma)"],
  ["NA", "Namibia"],
  ["NR", "Nauru"],
  ["NP", "Nepal"],
  ["NL", "Netherlands"],
  ["NC", "New Caledonia"],
  ["NZ", "New Zealand"],
  ["NI", "Nicaragua"],
  ["NE", "Niger"],
  ["NG", "Nigeria"],
  ["NU", "Niue"],
  ["NF", "Norfolk Island"],
  ["MK", "North Macedonia"],
  ["NO", "Norway"],
  ["OM", "Oman"],
  ["PK", "Pakistan"],
  ["PS", "Palestinian Territories"],
  ["PA", "Panama"],
  ["PG", "Papua New Guinea"],
  ["PY", "Paraguay"],
  ["PE", "Peru"],
  ["PH", "Philippines"],
  ["PN", "Pitcairn Islands"],
  ["PL", "Poland"],
  ["PT", "Portugal"],
  ["QA", "Qatar"],
  ["RE", "Réunion"],
  ["RO", "Romania"],
  ["RU", "Russia"],
  ["RW", "Rwanda"],
  ["WS", "Samoa"],
  ["SM", "San Marino"],
  ["ST", "São Tomé & Príncipe"],
  ["SA", "Saudi Arabia"],
  ["SN", "Senegal"],
  ["RS", "Serbia"],
  ["SC", "Seychelles"],
  ["SL", "Sierra Leone"],
  ["SG", "Singapore"],
  ["SX", "Sint Maarten"],
  ["SK", "Slovakia"],
  ["SI", "Slovenia"],
  ["SB", "Solomon Islands"],
  ["SO", "Somalia"],
  ["ZA", "South Africa"],
  ["GS", "South Georgia & South Sandwich Islands"],
  ["KR", "South Korea"],
  ["SS", "South Sudan"],
  ["ES", "Spain"],
  ["LK", "Sri Lanka"],
  ["BL", "St. Barthélemy"],
  ["SH", "St. Helena"],
  ["KN", "St. Kitts & Nevis"],
  ["LC", "St. Lucia"],
  ["MF", "St. Martin"],
  ["PM", "St. Pierre & Miquelon"],
  ["VC", "St. Vincent & Grenadines"],
  ["SD", "Sudan"],
  ["SR", "Suriname"],
  ["SJ", "Svalbard & Jan Mayen"],
  ["SE", "Sweden"],
  ["CH", "Switzerland"],
  ["TW", "Taiwan"],
  ["TJ", "Tajikistan"],
  ["TZ", "Tanzania"],
  ["TH", "Thailand"],
  ["TL", "Timor-Leste"],
  ["TG", "Togo"],
  ["TK", "Tokelau"],
  ["TO", "Tonga"],
  ["TT", "Trinidad & Tobago"],
  ["TA", "Tristan da Cunha"],
  ["TN", "Tunisia"],
  ["TR", "Turkey"],
  ["TM", "Turkmenistan"],
  ["TC", "Turks & Caicos Islands"],
  ["TV", "Tuvalu"],
  ["UM", "U.S. Outlying Islands"],
  ["UG", "Uganda"],
  ["UA", "Ukraine"],
  ["AE", "United Arab Emirates"],
  ["GB", "United Kingdom"],
  ["US", "United States"],
  ["UY", "Uruguay"],
  ["UZ", "Uzbekistan"],
  ["VU", "Vanuatu"],
  ["VA", "Vatican City"],
  ["VE", "Venezuela"],
  ["VN", "Vietnam"],
  ["WF", "Wallis & Futuna"],
  ["EH", "Western Sahara"],
  ["YE", "Yemen"],
  ["ZM", "Zambia"],
  ["ZW", "Zimbabwe"],
]);

const egyptianGovernorates = new Map([
  ["SU", "6th of October"],
  ["SHR", "Al Sharqia"],
  ["ALX", "Alexandria"],
  ["ASN", "Aswan"],
  ["AST", "Asyut"],
  ["BH", "Beheira"],
  ["BNS", "Beni Suef"],
  ["C", "Cairo"],
  ["DK", "Dakahlia"],
  ["DT", "Damietta"],
  ["FYM", "Faiyum"],
  ["GH", "Gharbia"],
  ["GZ", "Giza"],
  ["HU", "Helwan"],
  ["IS", "Ismailia"],
  ["KFS", "Kafr el-Sheikh"],
  ["LX", "Luxor"],
  ["MT", "Matrouh"],
  ["MN", "Minya"],
  ["MNF", "Monufia"],
  ["WAD", "New Valley"],
  ["SIN", "North Sinai"],
  ["PTS", "Port Said"],
  ["KB", "Qalyubia"],
  ["KN", "Qena"],
  ["BA", "Red Sea"],
  ["SHG", "Sohag"],
  ["JS", "South Sinai"],
  ["SUZ", "Suez"],
]);

const salvadoranDepartments = new Map([
  ["SV-AH", "Ahuachapán"],
  ["SV-CA", "Cabañas"],
  ["SV-CH", "Chalatenango"],
  ["SV-CU", "Cuscatlán"],
  ["SV-LI", "La Libertad"],
  ["SV-PA", "La Paz"],
  ["SV-UN", "La Unión"],
  ["SV-MO", "Morazán"],
  ["SV-SM", "San Miguel"],
  ["SV-SS", "San Salvador"],
  ["SV-SV", "San Vicente"],
  ["SV-SA", "Santa Ana"],
  ["SV-SO", "Sonsonate"],
  ["SV-US", "Usulután"],
]);

const frenchRegions = new Map([
  ["FR-ARA", "Auvergne-Rhône-Alpes"],
  ["FR-BFC", "Bourgogne-Franche-Comté"],
  ["FR-BRE", "Brittany"],
  ["FR-CVL", "Centre-Val de Loire"],
  ["FR-GES", "Grand Est"],
  ["FR-HDF", "Hauts-de-France"],
  ["FR-NOR", "Normandy"],
  ["FR-NAQ", "Nouvelle-Aquitaine"],
  ["FR-OCC", "Occitanie"],
  ["FR-PDL", "Pays de la Loire"],
  ["FR-PAC", "Provence-Alpes-Côte d'Azur"],
  ["FR-IDF", "Île-de-France"],
]);

const germanLands = new Map([
  ["BW", "Baden-Württemberg"],
  ["BY", "Bayern"],
  ["BE", "Berlin"],
  ["BB", "Brandenburg"],
  ["HB", "Bremen"],
  ["HH", "Hamburg"],
  ["HE", "Hessen"],
  ["MV", "Mecklenburg-Vorpommern"],
  ["NI", "Niedersachsen"],
  ["NW", "Nordrhein-Westfalen"],
  ["RP", "Rheinland-Pfalz"],
  ["SL", "Saarland"],
  ["SN", "Sachsen"],
  ["ST", "Sachsen-Anhalt"],
  ["SH", "Schleswig-Holstein"],
  ["TH", "Thüringen"],
]);

const guatemalanDepartments = new Map([
  ["AVE", "Alta Verapaz"],
  ["BVE", "Baja Verapaz"],
  ["CMT", "Chimaltenango"],
  ["CQM", "Chiquimula"],
  ["EPR", "El Progreso"],
  ["ESC", "Escuintla"],
  ["GUA", "Guatemala"],
  ["HUE", "Huehuetenango"],
  ["IZA", "Izabal"],
  ["JAL", "Jalapa"],
  ["JUT", "Jutiapa"],
  ["PET", "Petén"],
  ["QUE", "Quetzaltenango"],
  ["QUI", "Quiché"],
  ["RET", "Retalhuleu"],
  ["SAC", "Sacatepéquez"],
  ["SMA", "San Marcos"],
  ["SRO", "Santa Rosa"],
  ["SOL", "Sololá"],
  ["SUC", "Suchitepéquez"],
  ["TOT", "Totonicapán"],
  ["ZAC", "Zacapa"],
]);

const honduranDepartments = new Map([
  ["HN-AT", "Atlántida"],
  ["HN-CH", "Choluteca"],
  ["HN-CL", "Colón"],
  ["HN-CM", "Comayagua"],
  ["HN-CP", "Copán"],
  ["HN-CR", "Cortés"],
  ["HN-EP", "El Paraíso"],
  ["HN-FM", "Francisco Morazán"],
  ["HN-GD", "Gracias a Dios"],
  ["HN-IN", "Intibucá"],
  ["HN-IB", "Islas de la Bahía"],
  ["HN-LP", "La Paz"],
  ["HN-LE", "Lempira"],
  ["HN-OC", "Ocotepeque"],
  ["HN-OL", "Olancho"],
  ["HN-SB", "Santa Bárbara"],
  ["HN-VA", "Valle"],
  ["HN-YO", "Yoro"],
]);

const hongKongRegions = new Map([
  ["HK", "Honk Kong Island"],
  ["KLN", "Kowloon"],
  ["NT", "New Territories"],
  ["OTI", "Outlying Islands"],
]);

const indianStates = new Map([
  ["AN", "Andaman and Nicobar Islands"],
  ["AP", "Andhra Pradesh"],
  ["AR", "Arunachal Pradesh"],
  ["AS", "Assam"],
  ["BR", "Bihar"],
  ["CH", "Chandigarh"],
  ["CT", "Chhattisgarh"],
  ["DN", "Dadra and Nagar Haveli"],
  ["DD", "Daman & Diu"],
  ["DL", "Delhi"],
  ["GA", "Goa"],
  ["GJ", "Gujarat"],
  ["HR", "Haryana"],
  ["HP", "Himachal Pradesh"],
  ["JK", "Jammu & Kashmir"],
  ["JH", "Jharkhand"],
  ["KA", "Karnataka"],
  ["KL", "Kerala"],
  ["LA", "Ladakh"],
  ["LD", "Lakshadweep"],
  ["MP", "Madhya Pradesh"],
  ["MH", "Maharashtra"],
  ["MN", "Manipur"],
  ["ML", "Meghalaya"],
  ["MZ", "Mizoram"],
  ["NL", "Nagaland"],
  ["OR", "Orissa"],
  ["PY", "Pondicherry"],
  ["PB", "Punjab"],
  ["RJ", "Rajasthan"],
  ["SK", "Sikkim"],
  ["TN", "Tamil Nadu"],
  ["TS", "Telangana"],
  ["TR", "Tripura"],
  ["UP", "Uttar Pradesh"],
  ["UT", "Uttarakhand"],
  ["WB", "West Bengal"],
]);

const indonesianProvinces = new Map([
  ["AC", "Aceh"],
  ["BA", "Bali"],
  ["BT", "Banten"],
  ["BE", "Bengkulu"],
  ["GO", "Gorontalo"],
  ["JK", "Jakarta Raya"],
  ["JA", "Jambi"],
  ["JB", "Jawa Barat"],
  ["JT", "Jawa Tengah"],
  ["JI", "Jawa Timur"],
  ["KB", "Kalimantan Barat"],
  ["KS", "Kalimantan Selatan"],
  ["KT", "Kalimantan Tengah"],
  ["KI", "Kalimantan Timur"],
  ["KU", "Kalimantan Utara"],
  ["BB", "Kepulauan Bangka Belitung"],
  ["KR", "Kepulauan Riau"],
  ["LA", "Lampung"],
  ["MA", "Maluku"],
  ["MU", "Maluku Utara"],
  ["NB", "Nusa Tenggara Barat"],
  ["NT", "Nusa Tenggara Timur"],
  ["PA", "Papua"],
  ["PB", "Papua Barat"],
  ["RI", "Riau"],
  ["SR", "Sulawesi Barat"],
  ["SN", "Sulawesi Selatan"],
  ["ST", "Sulawesi Tengah"],
  ["SG", "Sulawesi Tenggara"],
  ["SA", "Sulawesi Utara"],
  ["SB", "Sumatera Barat"],
  ["SS", "Sumatera Selatan"],
  ["SU", "Sumatera Utara"],
  ["YO", "Yogyakarta"],
]);

const iraqiGovernorates = new Map([
  ["IQ-AN", "Al Anbār"],
  ["IQ-BA", "Al Başrah"],
  ["IQ-MU", "Al Muthanná"],
  ["IQ-QA", "Al Qādisīyah"],
  ["IQ-NA", "An Najaf"],
  ["IQ-AR", "Arbīl"],
  ["IQ-SU", "As Sulaymānīyah"],
  ["IQ-BG", "Baghdād"],
  ["IQ-BB", "Bābil"],
  ["IQ-DA", "Dahūk"],
  ["IQ-DQ", "Dhī Qār"],
  ["IQ-DA", "Dihok"],
  ["IQ-DI", "Diyālá"],
  ["IQ-AR", "Hewlêr"],
  ["IQ-KA", "Karbalā`"],
  ["IQ-KI", "Kirkūk"],
  ["IQ-MA", "Maysān"],
  ["IQ-NI", "Nīnawá"],
  ["IQ-SU", "Slêmanî"],
  ["IQ-WA", "Wāsiţ"],
  ["IQ-SD", "Şalāḩ ad Dīn"],
]);

const irishCounties = new Map([
  ["CW", "Carlow"],
  ["CN", "Cavan"],
  ["CE", "Clare"],
  ["C", "Cork"],
  ["DL", "Donegal"],
  ["D", "Dublin"],
  ["G", "Galway"],
  ["KY", "Kerry"],
  ["KE", "Kildare"],
  ["KK", "Kilkenny"],
  ["LS", "Laois"],
  ["LM", "Leitrim"],
  ["LK", "Limerick"],
  ["LD", "Longford"],
  ["LH", "Louth"],
  ["MO", "Mayo"],
  ["MH", "Meath"],
  ["MN", "Monaghan"],
  ["OY", "Offaly"],
  ["RN", "Roscommon"],
  ["SO", "Sligo"],
  ["TA", "Tipperary"],
  ["WD", "Waterford"],
  ["WH", "Westmeath"],
  ["WX", "Wexford"],
  ["WW", "Wicklow"],
]);

const italianProvinces = new Map([
  ["AG", "Agrigento"],
  ["AL", "Alessandria"],
  ["AN", "Ancona"],
  ["AO", "Aosta Valley"],
  ["AR", "Arezzo"],
  ["AP", "Ascoli Piceno"],
  ["AT", "Asti"],
  ["AV", "Avellino"],
  ["BA", "Bari"],
  ["BT", "Barletta-Andria-Trani"],
  ["BL", "Belluno"],
  ["BN", "Benevento"],
  ["BG", "Bergamo"],
  ["BI", "Biella"],
  ["BO", "Bologna"],
  ["BS", "Brescia"],
  ["BR", "Brindisi"],
  ["CA", "Cagliari"],
  ["CL", "Caltanissetta"],
  ["CB", "Campobasso"],
  ["CI", "Carbonia-Iglesias"],
  ["CE", "Caserta"],
  ["CT", "Catania"],
  ["CZ", "Catanzaro"],
  ["CH", "Chieti"],
  ["CO", "Como"],
  ["CS", "Cosenza"],
  ["CR", "Cremona"],
  ["KR", "Crotone"],
  ["CN", "Cuneo"],
  ["EN", "Enna"],
  ["FM", "Fermo"],
  ["FE", "Ferrara"],
  ["FI", "Florence"],
  ["FG", "Foggia"],
  ["FC", "Forlì-Cesena"],
  ["FR", "Frosinone"],
  ["GE", "Genoa"],
  ["GO", "Gorizia"],
  ["GR", "Grosseto"],
  ["IM", "Imperia"],
  ["IS", "Isernia"],
  ["SP", "La Spezia"],
  ["LT", "Latina"],
  ["LE", "Lecce"],
  ["LC", "Lecco"],
  ["LI", "Livorno"],
  ["LO", "Lodi"],
  ["LU", "Lucca"],
  ["AQ", "L'Aquila"],
  ["MC", "Macerata"],
  ["MN", "Mantua"],
  ["MS", "Massa and Carrara"],
  ["MT", "Matera"],
  ["VS", "Medio Campidano"],
  ["ME", "Messina"],
  ["MI", "Milan"],
  ["MO", "Modena"],
  ["MB", "Monza and Brianza"],
  ["NA", "Naples"],
  ["NO", "Novara"],
  ["NU", "Nuoro"],
  ["OG", "Ogliastra"],
  ["OT", "Olbia-Tempio"],
  ["OR", "Oristano"],
  ["PD", "Padua"],
  ["PA", "Palermo"],
  ["PR", "Parma"],
  ["PV", "Pavia"],
  ["PG", "Perugia"],
  ["PU", "Pesaro and Urbino"],
  ["PE", "Pescara"],
  ["PC", "Piacenza"],
  ["PI", "Pisa"],
  ["PT", "Pistoia"],
  ["PN", "Pordenone"],
  ["PZ", "Potenza"],
  ["PO", "Prato"],
  ["RG", "Ragusa"],
  ["RA", "Ravenna"],
  ["RC", "Reggio Calabria"],
  ["RE", "Reggio Emilia"],
  ["RI", "Rieti"],
  ["RN", "Rimini"],
  ["RM", "Rome"],
  ["RO", "Rovigo"],
  ["SA", "Salerno"],
  ["SS", "Sassari"],
  ["SV", "Savona"],
  ["SI", "Siena"],
  ["SO", "Sondrio"],
  ["BZ", "South Tyrol"],
  ["SR", "Syracuse"],
  ["TA", "Taranto"],
  ["TE", "Teramo"],
  ["TR", "Terni"],
  ["TP", "Trapani"],
  ["TN", "Trentino"],
  ["TV", "Treviso"],
  ["TS", "Trieste"],
  ["TO", "Turin"],
  ["UD", "Udine"],
  ["VA", "Varese"],
  ["VE", "Venice"],
  ["VB", "Verbano-Cusio-Ossola"],
  ["VC", "Vercelli"],
  ["VR", "Verona"],
  ["VV", "Vibo Valentia"],
  ["VI", "Vicenza"],
  ["VT", "Viterbo"],
]);

const jamaicanParishes = new Map([
  ["JM-13", "Clarendon"],
  ["JM-09", "Hanover"],
  ["JM-01", "Kingston"],
  ["JM-12", "Manchester"],
  ["JM-04", "Portland"],
  ["JM-02", "Saint Andrew"],
  ["JM-06", "Saint Ann"],
  ["JM-14", "Saint Catherine"],
  ["JM-11", "Saint Elizabeth"],
  ["JM-08", "Saint James"],
  ["JM-05", "Saint Mary"],
  ["JM-03", "Saint Thomas"],
  ["JM-07", "Trelawny"],
  ["JM-10", "Westmoreland"],
]);

const japanesePrefectures = new Map([
  ["JP-01", "Hokkaido"],
  ["JP-02", "Aomori"],
  ["JP-03", "Iwate"],
  ["JP-04", "Miyagi"],
  ["JP-05", "Akita"],
  ["JP-06", "Yamagata"],
  ["JP-07", "Fukushima"],
  ["JP-08", "Ibaraki"],
  ["JP-09", "Tochigi"],
  ["JP-10", "Gunma"],
  ["JP-11", "Saitama"],
  ["JP-12", "Chiba"],
  ["JP-13", "Tokyo"],
  ["JP-14", "Kanagawa"],
  ["JP-15", "Niigata"],
  ["JP-16", "Toyama"],
  ["JP-17", "Ishikawa"],
  ["JP-18", "Fukui"],
  ["JP-19", "Yamanashi"],
  ["JP-20", "Nagano"],
  ["JP-21", "Gifu"],
  ["JP-22", "Shizuoka"],
  ["JP-23", "Aichi"],
  ["JP-24", "Mie"],
  ["JP-25", "Shiga"],
  ["JP-26", "Kyoto"],
  ["JP-27", "Osaka"],
  ["JP-28", "Hyogo"],
  ["JP-29", "Nara"],
  ["JP-30", "Wakayama"],
  ["JP-31", "Tottori"],
  ["JP-32", "Shimane"],
  ["JP-33", "Okayama"],
  ["JP-34", "Hiroshima"],
  ["JP-35", "Yamaguchi"],
  ["JP-36", "Tokushima"],
  ["JP-37", "Kagawa"],
  ["JP-38", "Ehime"],
  ["JP-39", "Kochi"],
  ["JP-40", "Fukuoka"],
  ["JP-41", "Saga"],
  ["JP-42", "Nagasaki"],
  ["JP-43", "Kumamoto"],
  ["JP-44", "Oita"],
  ["JP-45", "Miyazaki"],
  ["JP-46", "Kagoshima"],
  ["JP-47", "Okinawa"],
]);

const kazakhstanRegions = new Map([
  ["KZ-AKM", "Akmolinskaja oblast'"],
  ["KZ-AKM", "Akmolinskaya oblast'"],
  ["KZ-AKT", "Aktjubinskaja oblast'"],
  ["KZ-AKT", "Aktyubinskaya oblast'"],
  ["KZ-ALM", "Almatinskaja oblast'"],
  ["KZ-ALM", "Almatinskaya oblast'"],
  ["KZ-ATY", "Atyrauskaja oblast'"],
  ["KZ-ATY", "Atyrauskaya oblast'"],
  ["KZ-KAR", "Karagandinskaja oblast'"],
  ["KZ-KAR", "Karagandinskaya oblast'"],
  ["KZ-KUS", "Kostanajskaja oblast'"],
  ["KZ-KUS", "Kostanayskaya oblast'"],
  ["KZ-KZY", "Kyzylordinskaja oblast'"],
  ["KZ-KZY", "Kyzylordinskaya oblast'"],
  ["KZ-MAN", "Mangistauskaya oblast'"],
  ["KZ-MAN", "Mangystauskaja oblast'"],
  ["KZ-PAV", "Pavlodarskaja oblast'"],
  ["KZ-PAV", "Pavlodarskaya oblast'"],
  ["KZ-SEV", "Severo-Kazahstanskaja oblast'"],
  ["KZ-SEV", "Severo-Kazakhstanskaya oblast'"],
  ["KZ-YUZ", "Turkestankaya oblast'"],
  ["KZ-YUZ", "Turkestanskaja oblast'"],
  ["KZ-VOS", "Vostochno-Kazakhstanskaya oblast'"],
  ["KZ-VOS", "Vostočno-Kazahstanskaja oblast'"],
  ["KZ-ZAP", "Zapadno-Kazahstanskaja oblast'"],
  ["KZ-ZAP", "Zapadno-Kazakhstanskaya oblast'"],
  ["KZ-ZHA", "Zhambylskaya oblast'"],
  ["KZ-ZHA", "Žambylskaja oblast'"],
]);

const kiribatianIslands = new Map([
  ["KI-G", "Gilbert Islands"],
  ["KI-L", "Line Islands"],
  ["KI-P", "Phoenix Islands"],
]);

const malaysianStates = new Map([
  ["JHR", "Johor"],
  ["KDH", "Kedah"],
  ["KTN", "Kelantan"],
  ["MLK", "Malacca"],
  ["NSN", "Nigeri Sembilan"],
  ["PHG", "Pahang"],
  ["PNG", "Penang"],
  ["PRK", "Perak"],
  ["PLS", "Perlis"],
  ["SGR", "Selangor"],
  ["TRG", "Terengganu"],
  ["SBH", "Sabah"],
  ["SWK", "Sarawak"],
  ["KUL", "Kuala Lumpur"],
  ["LBN", "Labuan"],
  ["PJY", "Putrajaya"],
]);

const mexicanStates = new Map([
  ["BCS", "Aguascalientes"],
  ["BC", "Baja California"],
  ["BNC", "Baja California Sur"],
  ["CAMP", "Campeche"],
  ["CHIS", "Chiapas"],
  ["CHIH", "Chihuahua"],
  ["DF", "Ciudad de Mexico"],
  ["COAH", "Coahuila"],
  ["COL", "Colima"],
  ["DGO", "Durango"],
  ["GTO", "Guanajuato"],
  ["GRO", "Guerrero"],
  ["HGO", "Hidalgo"],
  ["JAL", "Jalisco"],
  ["MEX", "Mexico State"],
  ["MICH", "Michoacan"],
  ["MOR", "Morelos"],
  ["NAY", "Nayarit"],
  ["NL", "Nuevo Leon"],
  ["OAX", "Oaxaca"],
  ["PUE", "Puebla"],
  ["QRO", "Querétaro"],
  ["Q ROO", "Quintana Roo"],
  ["SLP", "San Luis Potosi"],
  ["SIN", "Sinaloa"],
  ["SON", "Sonora"],
  ["TAB", "Tabasco"],
  ["TAMPS", "Tamaulipas"],
  ["TLAX", "Tlaxcala"],
  ["VER", "Veracruz"],
  ["YUC", "Yucatan"],
  ["ZAC", "Zacatecas"],
]);

const mongolianProvinces = new Map([
  ["MN-073", "Arhangay"],
  ["MN-071", "Bayan-Ölgiy"],
  ["MN-069", "Bayanhongor"],
  ["MN-067", "Bulgan"],
  ["MN-037", "Darhan uul"],
  ["MN-061", "Dornod"],
  ["MN-063", "Dornogovĭ"],
  ["MN-059", "Dundgovĭ"],
  ["MN-057", "Dzavhan"],
  ["MN-065", "Govĭ-Altay"],
  ["MN-064", "Govĭ-Sümber"],
  ["MN-039", "Hentiy"],
  ["MN-043", "Hovd"],
  ["MN-041", "Hövsgöl"],
  ["MN-035", "Orhon"],
  ["MN-049", "Selenge"],
  ["MN-051", "Sühbaatar"],
  ["MN-047", "Töv"],
  ["MN-046", "Uvs"],
  ["MN-053", "Ömnögovĭ"],
  ["MN-055", "Övörhangay"],
]);

const mozambicanProvinces = new Map([
  ["MZ-P", "Cabo Delgado"],
  ["MZ-G", "Gaza"],
  ["MZ-I", "Inhambane"],
  ["MZ-B", "Manica"],
  ["MZ-L", "Maputo"],
  ["MZ-N", "Nampula"],
  ["MZ-A", "Niassa"],
  ["MZ-S", "Sofala"],
  ["MZ-T", "Tete"],
  ["MZ-Q", "Zambézia"],
]);

const nauruanDistricts = new Map([
  ["NR-01", "Aiwo"],
  ["NR-02", "Anabar"],
  ["NR-03", "Anetan"],
  ["NR-04", "Anibare"],
  ["NR-05", "Baitsi"],
  ["NR-06", "Boe"],
  ["NR-07", "Buada"],
  ["NR-08", "Denigomodu"],
  ["NR-09", "Ewa"],
  ["NR-10", "Ijuw"],
  ["NR-11", "Meneng"],
  ["NR-12", "Nibok"],
  ["NR-13", "Uaboe"],
  ["NR-14", "Yaren"],
]);

const newZealandProvinces = new Map([
  ["AUK", "Auckland"],
  ["BOP", "Bay of Plenty"],
  ["CAN", "Canterbury"],
  ["CIT", "Chatham Islands"],
  ["GIS", "Gisborne"],
  ["HKB", "Hawke's Bay"],
  ["MWT", "Manawatu-Wanganui"],
  ["MBH", "Marlborough"],
  ["NSN", "Nelson"],
  ["NTL", "Northland"],
  ["OTA", "Otago"],
  ["STL", "Southland"],
  ["TKI", "Taranaki"],
  ["TAS", "Tasman"],
  ["WKO", "Waikato"],
  ["WGN", "Wellington"],
  ["WTC", "West Coast"],
]);

const nicaraguanDepartments = new Map([
  ["NI-BO", "Boaco"],
  ["NI-CA", "Carazo"],
  ["NI-CI", "Chinandega"],
  ["NI-CO", "Chontales"],
  ["NI-ES", "Estelí"],
  ["NI-GR", "Granada"],
  ["NI-JI", "Jinotega"],
  ["NI-LE", "León"],
  ["NI-MD", "Madriz"],
  ["NI-MN", "Managua"],
  ["NI-MS", "Masaya"],
  ["NI-MT", "Matagalpa"],
  ["NI-NS", "Nueva Segovia"],
  ["NI-RI", "Rivas"],
  ["NI-SJ", "Río San Juan"],
]);

const nigerianStates = new Map([
  ["AB", "Abia"],
  ["AD", "Adamawa"],
  ["AK", "Akwa Ibom"],
  ["AN", "Anambra"],
  ["BA", "Bauchi"],
  ["BY", "Bayelsa"],
  ["BE", "Benue"],
  ["BO", "Borno"],
  ["CR", "Cross River"],
  ["DE", "Delta"],
  ["EB", "Ebonyi"],
  ["ED", "Edo"],
  ["EK", "Ekiti"],
  ["EN", "Enugu"],
  ["FC", "Federal Capital Territory"],
  ["GO", "Gombe"],
  ["IM", "Imo"],
  ["JI", "Jigawa"],
  ["KD", "Kaduna"],
  ["KN", "Kano"],
  ["KT", "Katsina"],
  ["KE", "Kebbi"],
  ["KO", "Kogi"],
  ["KW", "Kwara"],
  ["LA", "Lagos"],
  ["NA", "Nasarawa"],
  ["NI", "Niger"],
  ["OG", "Ogun"],
  ["ON", "Ondo"],
  ["OS", "Osun"],
  ["OY", "Oyo"],
  ["PL", "Plateau"],
  ["RI", "Rivers"],
  ["SO", "Sokoto"],
  ["TA", "Taraba"],
  ["YO", "Yobe"],
  ["ZA", "Zamfara"],
]);

const panamanianProvinces = new Map([
  ["PA-1", "Bocas del Toro"],
  ["PA-4", "Chiriquí"],
  ["PA-2", "Coclé"],
  ["PA-3", "Colón"],
  ["PA-5", "Darién"],
  ["PA-EM", "Emberá"],
  ["PA-KY", "Guna Yala"],
  ["PA-6", "Herrera"],
  ["PA-7", "Los Santos"],
  ["PA-NB", "Ngöbe-Buglé"],
  ["PA-8", "Panamá"],
  ["PA-9", "Veraguas"],
  ["PA-10", "West Panamá"],
]);

const papaNewGuineanProvinces = new Map([
  ["PG-CPM", "Central"],
  ["PG-CPK", "Chimbu"],
  ["PG-EBR", "East New Britain"],
  ["PG-ESW", "East Sepik"],
  ["PG-EHG", "Eastern Highlands"],
  ["PG-EPW", "Enga"],
  ["PG-GPK", "Gulf"],
  ["PG-HLA", "Hela"],
  ["PG-JWK", "Jiwaka"],
  ["PG-MPM", "Madang"],
  ["PG-MRL", "Manus"],
  ["PG-MBA", "Milne Bay"],
  ["PG-MPL", "Morobe"],
  ["PG-NIK", "New Ireland"],
  ["PG-NPP", "Northern"],
  ["PG-SHM", "Southern Highlands"],
  ["PG-WBK", "West New Britain"],
  ["PG-SAN", "West Sepik"],
  ["PG-WPD", "Western"],
  ["PG-WHM", "Western Highlands"],
]);

const peruvianRegions = new Map([
  ["PE-AMA", "Amazonas"],
  ["PE-ANC", "Ancash"],
  ["PE-APU", "Apurímac"],
  ["PE-ARE", "Arequipa"],
  ["PE-AYA", "Ayacucho"],
  ["PE-CAJ", "Cajamarca"],
  ["PE-CUS", "Cusco"],
  ["PE-CAL", "El Callao"],
  ["PE-HUV", "Huancavelica"],
  ["PE-HUC", "Huánuco"],
  ["PE-ICA", "Ica"],
  ["PE-JUN", "Junín"],
  ["PE-LAL", "La Libertad"],
  ["PE-LAM", "Lambayeque"],
  ["PE-LIM", "Lima (Department)"],
  ["PE-LMA", "Lima (Metropolitan)"],
  ["PE-LOR", "Loreto"],
  ["PE-MDD", "Madre de Dios"],
  ["PE-MOQ", "Moquegua"],
  ["PE-PAS", "Pasco"],
  ["PE-PIU", "Piura"],
  ["PE-PUN", "Puno"],
  ["PE-SAM", "San Martín"],
  ["PE-TAC", "Tacna"],
  ["PE-TUM", "Tumbes"],
  ["PE-UCA", "Ucayali"],
]);

const philippineRegions = new Map([
  ["PH-ABR", "Abra"],
  ["PH-AGN", "Agusan del Norte"],
  ["PH-AGS", "Agusan del Sur"],
  ["PH-AKL", "Aklan"],
  ["PH-ALB", "Albay"],
  ["PH-ANT", "Antique"],
  ["PH-APA", "Apayao"],
  ["PH-AUR", "Aurora"],
  ["PH-BAS", "Basilan"],
  ["PH-BAN", "Bataan"],
  ["PH-BTN", "Batanes"],
  ["PH-BTG", "Batangas"],
  ["PH-BEN", "Benguet"],
  ["PH-BIL", "Biliran"],
  ["PH-BOH", "Bohol"],
  ["PH-BUK", "Bukidnon"],
  ["PH-BUL", "Bulacan"],
  ["PH-CAG", "Cagayan"],
  ["PH-CAN", "Camarines Norte"],
  ["PH-CAS", "Camarines Sur"],
  ["PH-CAM", "Camiguin"],
  ["PH-CAP", "Capiz"],
  ["PH-CAT", "Catanduanes"],
  ["PH-CAV", "Cavite"],
  ["PH-CEB", "Cebu"],
  ["PH-COM", "Compostela Valley"],
  ["PH-NCO", "Cotabato"],
  ["PH-DVO", "Davao Occidental"],
  ["PH-DAO", "Davao Oriental"],
  ["PH-DAV", "Davao del Norte"],
  ["PH-DAS", "Davao del Sur"],
  ["PH-DIN", "Dinagat Islands"],
  ["PH-EAS", "Eastern Samar"],
  ["PH-GUI", "Guimaras"],
  ["PH-IFU", "Ifugao"],
  ["PH-ILN", "Ilocos Norte"],
  ["PH-ILS", "Ilocos Sur"],
  ["PH-ILI", "Iloilo"],
  ["PH-ISA", "Isabela"],
  ["PH-KAL", "Kalinga"],
  ["PH-LUN", "La Union"],
  ["PH-LAG", "Laguna"],
  ["PH-LAN", "Lanao del Norte"],
  ["PH-LAS", "Lanao del Sur"],
  ["PH-LEY", "Leyte"],
  ["PH-MAG", "Maguindanao"],
  ["PH-MAD", "Marinduque"],
  ["PH-MAS", "Masbate"],
  ["PH-00", "Metro Manila"],
  ["PH-MSC", "Misamis Occidental"],
  ["PH-MSR", "Misamis Oriental"],
  ["PH-MOU", "Mountain"],
  ["PH-NEC", "Negros Occidental"],
  ["PH-NER", "Negros Oriental"],
  ["PH-NSA", "Northern Samar"],
  ["PH-NUE", "Nueva Ecija"],
  ["PH-NUV", "Nueva Vizcaya"],
  ["PH-MDC", "Occidental Mindoro"],
  ["PH-MDR", "Oriental Mindoro"],
  ["PH-PLW", "Palawan"],
  ["PH-PAM", "Pampanga"],
  ["PH-PAN", "Pangasinan"],
  ["PH-QUE", "Quezon"],
  ["PH-QUI", "Quirino"],
  ["PH-RIZ", "Rizal"],
  ["PH-ROM", "Romblon"],
  ["PH-WSA", "Samar"],
  ["PH-SAR", "Sarangani"],
  ["PH-SIG", "Siquijor"],
  ["PH-SOR", "Sorsogon"],
  ["PH-SCO", "South Cotabato"],
  ["PH-SLE", "Southern Leyte"],
  ["PH-SUK", "Sultan Kudarat"],
  ["PH-SLU", "Sulu"],
  ["PH-SUN", "Surigao del Norte"],
  ["PH-SUR", "Surigao del Sur"],
  ["PH-TAR", "Tarlac"],
  ["PH-TAW", "Tawi-Tawi"],
  ["PH-ZMB", "Zambales"],
  ["PH-ZSI", "Zamboanga Sibugay"],
  ["PH-ZAN", "Zamboanga del Norte"],
  ["PH-ZAS", "Zamboanga del Sur"],
]);

const polishVoivodships = new Map([
  ["PL-02", "Lower Silesia"],
  ["PL-04", "Kuyavia-Pomerania"],
  ["PL-06", "Lublin"],
  ["PL-08", "Lubusz"],
  ["PL-10", "Lodz"],
  ["PL-14", "Lesser Poland"],
  ["PL-12", "Mazovia"],
  ["PL-16", "Opole"],
  ["PL-18", "Podkarpackie"],
  ["PL-20", "Podlachia"],
  ["PL-22", "Pomeranian"],
  ["PL-24", "Silesian"],
  ["PL-26", "Swietokrzyskie"],
  ["PL-28", "Warmian-Masurian"],
  ["PL-30", "Greater Poland"],
  ["PL-32", "West Pomeranian"],
]);

const portugueseRegions = new Map([
  ["PT-01", "Aveiro"],
  ["PT-20", "Azores"],
  ["PT-02", "Beja"],
  ["PT-03", "Braga"],
  ["PT-04", "Bragança"],
  ["PT-05", "Castelo Branco"],
  ["PT-06", "Coimbra"],
  ["PT-07", "Évora"],
  ["PT-08", "Faro"],
  ["PT-09", "Guarda"],
  ["PT-10", "Leiria"],
  ["PT-11", "Lisbon"],
  ["PT-30", "Madeira"],
  ["PT-12", "Portalegre"],
  ["PT-13", "Porto"],
  ["PT-14", "Santarém"],
  ["PT-15", "Setúbal"],
  ["PT-16", "Viana do Castelo"],
  ["PT-17", "Vila Real"],
  ["PT-18", "Viseu"],
]);

const romanianCounties = new Map([
  ["AB", "Alba"],
  ["AR", "Arad"],
  ["AG", "Argeș"],
  ["BC", "Bacău"],
  ["BH", "Bihor"],
  ["BN", "Bistriţa-Năsăud"],
  ["BT", "Botoşani"],
  ["BR", "Brăila"],
  ["BV", "Braşov"],
  ["B", "Bucharest"],
  ["BZ", "Buzău"],
  ["CS", "Caraș-Severin"],
  ["CJ", "Cluj"],
  ["CT", "Constanța"],
  ["CV", "Covasna"],
  ["CL", "Călărași"],
  ["DJ", "Dolj"],
  ["DB", "Dâmbovița"],
  ["GL", "Galați"],
  ["GR", "Giurgiu"],
  ["GJ", "Gorj"],
  ["HR", "Harghita"],
  ["HD", "Hunedoara"],
  ["IL", "Ialomița"],
  ["IS", "Iași"],
  ["IF", "Ilfov"],
  ["MM", "Maramureş"],
  ["MH", "Mehedinți"],
  ["MS", "Mureş"],
  ["NT", "Neamţ"],
  ["OT", "Olt"],
  ["PH", "Prahova"],
  ["SJ", "Sălaj"],
  ["SM", "Satu Mare"],
  ["SB", "Sibiu"],
  ["SV", "Suceava"],
  ["TR", "Teleorman"],
  ["TM", "Timiș"],
  ["TL", "Tulcea"],
  ["VL", "Vâlcea"],
  ["VS", "Vaslui"],
  ["VN", "Vrancea"],
]);

const russianRegions = new Map([
  ["AD", "Adygea"],
  ["AL", "Altai"],
  ["ALT", "Altai Krai"],
  ["AMU", "Amur"],
  ["ARK", "Arkhangelsk"],
  ["AST", "Astrakhan"],
  ["BA", "Bashkortostan"],
  ["BEL", "Belgorod"],
  ["BRY", "Bryansk"],
  ["BU", "Buryat"],
  ["CE", "Chechen"],
  ["CHE", "Chelyabinsk"],
  ["CHU", "Chukotka Okrug"],
  ["CU", "Chuvash"],
  ["DA", "Dagestan"],
  ["IN", "Ingushetia"],
  ["IRK", "Irkutsk"],
  ["IVA", "Ivanovo"],
  ["YEV", "Jewish"],
  ["KB", "Kabardino-Balkar"],
  ["KGD", "Kaliningrad"],
  ["KL", "Kalmykia"],
  ["KLU", "Kaluga"],
  ["KAM", "Kamchatka Krai"],
  ["KC", "Karachay-Cherkess"],
  ["KR", "Karelia"],
  ["KEM", "Kemerovo"],
  ["KHA", "Khabarovsk Krai"],
  ["KK", "Khakassia"],
  ["KHM", "Khanty-Mansi"],
  ["KIR", "Kirov"],
  ["KO", "Komi"],
  ["KOS", "Kostroma"],
  ["KDA", "Krasnodar Krai"],
  ["KYA", "Krasnoyarsk Krai"],
  ["KGN", "Kurgan"],
  ["KRS", "Kursk"],
  ["LEN", "Leningrad"],
  ["LIP", "Lipetsk"],
  ["MAG", "Magadan"],
  ["ME", "Mari El"],
  ["MO", "Mordovia"],
  ["MOW", "Moscow"],
  ["MOS", "Moscow Province"],
  ["MUR", "Murmansk"],
  ["NIZ", "Nizhny Novgorod"],
  ["SE", "North Ossetia-Alania"],
  ["NGR", "Novgorod"],
  ["NVS", "Novosibirsk"],
  ["OMS", "Omsk"],
  ["ORE", "Orenburg"],
  ["ORL", "Oryol"],
  ["PNZ", "Penza"],
  ["PER", "Perm Krai"],
  ["PRI", "Primorsky Krai"],
  ["PSK", "Pskov"],
  ["ROS", "Rostov"],
  ["RYA", "Ryazan"],
  ["SPE", "Saint Petersburg"],
  ["SA", "Sakha"],
  ["SAK", "Sakhalin"],
  ["SAM", "Samara"],
  ["SAR", "Saratov"],
  ["SMO", "Smolensk"],
  ["STA", "Stavropol Krai"],
  ["SVE", "Sverdlovsk"],
  ["TAM", "Tambov"],
  ["TA", "Tatarstan"],
  ["TOM", "Tomsk"],
  ["TUL", "Tula"],
  ["TY", "Tuva"],
  ["TVE", "Tver"],
  ["TYU", "Tyumen"],
  ["UD", "Udmurt"],
  ["ULY", "Ulyanovsk"],
  ["VLA", "Vladimir"],
  ["VGG", "Volgograd"],
  ["VLG", "Vologda"],
  ["VOR", "Voronezh"],
  ["YAN", "Yamalo-Nenets Okrug"],
  ["YAR", "Yaroslavl"],
  ["ZAB", "Zabaykalsky Krai"],
]);

const saintKittAndNevisParishes = new Map([
  ["KN-01", "Christ Church Nichola Town"],
  ["KN-02", "Saint Anne Sandy Point"],
  ["KN-03", "Saint George Basseterre"],
  ["KN-04", "Saint George Gingerland"],
  ["KN-05", "Saint James Windward"],
  ["KN-06", "Saint John Capisterre"],
  ["KN-07", "Saint John Figtree"],
  ["KN-08", "Saint Mary Cayon"],
  ["KN-09", "Saint Paul Capisterre"],
  ["KN-10", "Saint Paul Charlestown"],
  ["KN-11", "Saint Peter Basseterre"],
  ["KN-12", "Saint Thomas Lowland"],
  ["KN-13", "Saint Thomas Middle Island"],
  ["KN-15", "Trinity Palmetto Point"],
]);

const somalianRegions = new Map([
  ["SO-AW", "Awdal"],
  ["SO-BK", "Bakool"],
  ["SO-BN", "Banaadir"],
  ["SO-BR", "Bari"],
  ["SO-BY", "Bay"],
  ["SO-GA", "Galguduud"],
  ["SO-GE", "Gedo"],
  ["SO-HI", "Hiiraan"],
  ["SO-JD", "Jubbada Dhexe"],
  ["SO-JH", "Jubbada Hoose"],
  ["SO-MU", "Mudug"],
  ["SO-NU", "Nugaal"],
  ["SO-SA", "Sanaag"],
  ["SO-SD", "Shabeellaha Dhexe"],
  ["SO-SH", "Shabeellaha Hoose"],
  ["SO-SO", "Sool"],
  ["SO-TO", "Togdheer"],
  ["SO-WO", "Woqooyi Galbeed"],
]);

const southAfricanProvinces = new Map([
  ["EC", "Eastern Cape"],
  ["FS", "Free State"],
  ["GP", "Gauteng"],
  ["NL", "KwaZulu-Natal"],
  ["LP", "Limpopo"],
  ["MP", "Mpumalanga"],
  ["NC", "Northern Cape"],
  ["NW", "North-West"],
  ["WC", "Western Cape"],
]);

const southKoreanProvinces = new Map([
  ["KR-26", "Busan"],
  ["KR-27", "Daegu"],
  ["KR-30", "Daejeon"],
  ["KR-42", "Gangwon"],
  ["KR-29", "Gwangju City"],
  ["KR-41", "Gyeonggi"],
  ["KR-28", "Incheon"],
  ["KR-49", "Jeju"],
  ["KR-43", "North Chungcheong"],
  ["KR-47", "North Gyeongsang"],
  ["KR-45", "North Jeolla"],
  ["KR-50", "Sejong"],
  ["KR-11", "Seoul"],
  ["KR-44", "South Chungcheong"],
  ["KR-48", "South Gyeongsang"],
  ["KR-46", "South Jeolla"],
  ["KR-31", "Ulsan"],
]);

const spanishProvinces = new Map([
  ["C", "A Coruna"],
  ["VI", "Alava"],
  ["AB", "Albacete"],
  ["A", "Alicante"],
  ["AL", "Almeria"],
  ["O", "Asturias"],
  ["AV", "Avila"],
  ["BA", "Badajoz"],
  ["PM", "Baleares"],
  ["B", "Barcelona"],
  ["BU", "Burgos"],
  ["CC", "Caceres"],
  ["CA", "Cadiz"],
  ["S", "Cantabria"],
  ["CS", "Castellon"],
  ["CE", "Ceuta"],
  ["CR", "Ciudad Real"],
  ["CO", "Cordoba"],
  ["CU", "Cuenca"],
  ["GI", "Girona"],
  ["GR", "Granada"],
  ["GU", "Guadalajara"],
  ["SS", "Guipuzcoa"],
  ["H", "Huelva"],
  ["HU", "Huesca"],
  ["J", "Jaen"],
  ["LO", "La Rioja"],
  ["GC", "Las Palmas"],
  ["LE", "Leon"],
  ["L", "Lleida"],
  ["LU", "Lugo"],
  ["M", "Madrid"],
  ["MA", "Malaga"],
  ["ML", "Melilla"],
  ["MU", "Murcia"],
  ["NA", "Navarra"],
  ["OR", "Ourense"],
  ["P", "Palencia"],
  ["PO", "Pontevedra"],
  ["SA", "Salamanca"],
  ["TF", "Santa Cruz de Tenerife"],
  ["SG", "Segovia"],
  ["SE", "Sevilla"],
  ["SO", "Soria"],
  ["T", "Tarragona"],
  ["TE", "Teruel"],
  ["TO", "Toledo"],
  ["V", "Valencia"],
  ["VA", "Valladolid"],
  ["BI", "Vizcaya"],
  ["ZA", "Zamora"],
  ["Z", "Zaragoza"],
]);

const surinameseDistricts = new Map([
  ["SR-BR", "Brokopondo"],
  ["SR-CM", "Commewijne"],
  ["SR-CR", "Coronie"],
  ["SR-MA", "Marowijne"],
  ["SR-NI", "Nickerie"],
  ["SR-PR", "Para"],
  ["SR-PM", "Paramaribo"],
  ["SR-SA", "Saramacca"],
  ["SR-SI", "Sipaliwini"],
  ["SR-WA", "Wanica"],
]);

const swissCantons = new Map([
  ["AG", "Aargau"],
  ["AR", "Appenzell Ausserrhoden"],
  ["AI", "Appenzell Innerrhoden"],
  ["BL", "Basel-Landschaft"],
  ["BS", "Basel-Stadt"],
  ["BE", "Bern"],
  ["FR", "Fribourg"],
  ["GE", "Geneva"],
  ["GL", "Glarus"],
  ["GR", "Graubunden"],
  ["JU", "Jura"],
  ["LU", "Luzern"],
  ["NE", "Neuchatel"],
  ["NW", "Nidwalden"],
  ["OW", "Obwalden"],
  ["SG", "St. Gallen"],
  ["SH", "Schaffhausen"],
  ["SO", "Solothurn"],
  ["SZ", "Schwyz"],
  ["TG", "Thurgau"],
  ["TI", "Ticino"],
  ["UR", "Uri"],
  ["VD", "Vaud"],
  ["VS", "Valais"],
  ["ZG", "Zug"],
  ["ZH", "Zurich"],
]);

const thaiProvinces = new Map([
  ["TH-37", "Amnat Charoen"],
  ["TH-15", "Ang Thong"],
  ["TH-10", "Bangkok"],
  ["TH-38", "Bueng Kan"],
  ["TH-31", "Buri Ram"],
  ["TH-24", "Chachoengsao"],
  ["TH-18", "Chai Nat"],
  ["TH-36", "Chaiyaphum"],
  ["TH-22", "Chanthaburi"],
  ["TH-50", "Chiang Mai"],
  ["TH-57", "Chiang Rai"],
  ["TH-20", "Chon Buri"],
  ["TH-86", "Chumphon"],
  ["TH-46", "Kalasin"],
  ["TH-62", "Kamphaeng Phet"],
  ["TH-71", "Kanchanaburi"],
  ["TH-40", "Khon Kaen"],
  ["TH-81", "Krabi"],
  ["TH-52", "Lampang"],
  ["TH-51", "Lamphun"],
  ["TH-42", "Loei"],
  ["TH-16", "Lopburi"],
  ["TH-58", "Mae Hong Son"],
  ["TH-44", "Maha Sarakham"],
  ["TH-49", "Mukdahan"],
  ["TH-26", "Nakhon Nayok"],
  ["TH-73", "Nakhon Pathom"],
  ["TH-48", "Nakhon Phanom"],
  ["TH-30", "Nakhon Ratchasima"],
  ["TH-60", "Nakhon Sawan"],
  ["TH-80", "Nakhon Si Thammarat"],
  ["TH-55", "Nan"],
  ["TH-96", "Narathiwat"],
  ["TH-39", "Nong Bua Lam Phu"],
  ["TH-43", "Nong Khai"],
  ["TH-12", "Nonthaburi"],
  ["TH-13", "Pathum Thani"],
  ["TH-94", "Pattani"],
  ["TH-S", "Pattaya"],
  ["TH-82", "Phang Nga"],
  ["TH-93", "Phatthalung"],
  ["TH-56", "Phayao"],
  ["TH-67", "Phetchabun"],
  ["TH-76", "Phetchaburi"],
  ["TH-66", "Phichit"],
  ["TH-65", "Phitsanulok"],
  ["TH-14", "Phra Nakhon Si Ayutthaya"],
  ["TH-54", "Phrae"],
  ["TH-83", "Phuket"],
  ["TH-25", "Prachin Buri"],
  ["TH-77", "Prachuap Khiri Khan"],
  ["TH-85", "Ranong"],
  ["TH-70", "Ratchaburi"],
  ["TH-21", "Rayong"],
  ["TH-45", "Roi Et"],
  ["TH-27", "Sa Kaeo"],
  ["TH-47", "Sakon Nakhon"],
  ["TH-11", "Samut Prakan"],
  ["TH-74", "Samut Sakhon"],
  ["TH-75", "Samut Songkhram"],
  ["TH-19", "Saraburi"],
  ["TH-91", "Satun"],
  ["TH-33", "Si Sa Ket"],
  ["TH-17", "Sing Buri"],
  ["TH-90", "Songkhla"],
  ["TH-64", "Sukhothai"],
  ["TH-72", "Suphanburi"],
  ["TH-84", "Surat Thani"],
  ["TH-32", "Surin"],
  ["TH-63", "Tak"],
  ["TH-92", "Trang"],
  ["TH-23", "Trat"],
  ["TH-34", "Ubon Ratchathani"],
  ["TH-41", "Udon Thani"],
  ["TH-61", "Uthai Thani"],
  ["TH-53", "Uttaradit"],
  ["TH-95", "Yala"],
  ["TH-35", "Yasothon"],
]);

const turkishProvinces = new Map([
  ["TR-01", "Adana"],
  ["TR-02", "Adiyaman"],
  ["TR-03", "Afyonkarahisar"],
  ["TR-68", "Aksaray"],
  ["TR-05", "Amasya"],
  ["TR-06", "Ankara"],
  ["TR-07", "Antalya"],
  ["TR-75", "Ardahan"],
  ["TR-08", "Artvin"],
  ["TR-09", "Aydin"],
  ["TR-04", "Ağri"],
  ["TR-10", "Balikesir"],
  ["TR-74", "Bartin"],
  ["TR-72", "Batman"],
  ["TR-69", "Bayburt"],
  ["TR-11", "Bilecik"],
  ["TR-12", "Bingöl"],
  ["TR-13", "Bitlis"],
  ["TR-14", "Bolu"],
  ["TR-15", "Burdur"],
  ["TR-16", "Bursa"],
  ["TR-20", "Denizli"],
  ["TR-21", "Diyarbakir"],
  ["TR-81", "Düzce"],
  ["TR-22", "Edirne"],
  ["TR-23", "Elaziğ"],
  ["TR-24", "Erzincan"],
  ["TR-25", "Erzurum"],
  ["TR-26", "Eskişehir"],
  ["TR-27", "Gaziantep"],
  ["TR-28", "Giresun"],
  ["TR-29", "Gümüşhane"],
  ["TR-30", "Hakkâri"],
  ["TR-31", "Hatay"],
  ["TR-32", "Isparta"],
  ["TR-76", "Iğdir"],
  ["TR-46", "Kahramanmaraş"],
  ["TR-78", "Karabük"],
  ["TR-70", "Karaman"],
  ["TR-36", "Kars"],
  ["TR-37", "Kastamonu"],
  ["TR-38", "Kayseri"],
  ["TR-79", "Kilis"],
  ["TR-41", "Kocaeli"],
  ["TR-42", "Konya"],
  ["TR-43", "Kütahya"],
  ["TR-39", "Kirklareli"],
  ["TR-71", "Kirikkale"],
  ["TR-40", "Kirşehir"],
  ["TR-44", "Malatya"],
  ["TR-45", "Manisa"],
  ["TR-47", "Mardin"],
  ["TR-33", "Mersin"],
  ["TR-48", "Muğla"],
  ["TR-49", "Muş"],
  ["TR-50", "Nevşehir"],
  ["TR-51", "Niğde"],
  ["TR-52", "Ordu"],
  ["TR-80", "Osmaniye"],
  ["TR-53", "Rize"],
  ["TR-54", "Sakarya"],
  ["TR-55", "Samsun"],
  ["TR-56", "Siirt"],
  ["TR-57", "Sinop"],
  ["TR-58", "Sivas"],
  ["TR-59", "Tekirdağ"],
  ["TR-60", "Tokat"],
  ["TR-61", "Trabzon"],
  ["TR-62", "Tunceli"],
  ["TR-64", "Uşak"],
  ["TR-65", "Van"],
  ["TR-77", "Yalova"],
  ["TR-66", "Yozgat"],
  ["TR-67", "Zonguldak"],
  ["TR-17", "Çanakkale"],
  ["TR-18", "Çankiri"],
  ["TR-19", "Çorum"],
  ["TR-34", "İstanbul"],
  ["TR-35", "İzmir"],
  ["TR-63", "Şanliurfa"],
  ["TR-73", "Şirnak"],
]);

const tuvaluanIslands = new Map([
  ["TV-NMG", "Nanumaga"],
  ["TV-NMA", "Nanumea"],
  ["TV-NIT", "Niutao"],
  ["TV-NUI", "Nui"],
  ["TV-NKF", "Nukufetau"],
  ["TV-NKL", "Nukulaelae"],
  ["TV-VAI", "Vaitupu"],
]);

const ukrainianRegions = new Map([
  ["UA-71", "Cherkaska oblast"],
  ["UA-74", "Chernihivska oblast"],
  ["UA-77", "Chernivetska oblast"],
  ["UA-12", "Dnipropetrovska oblast"],
  ["UA-14", "Donetska oblast"],
  ["UA-26", "Ivano-Frankivska oblast"],
  ["UA-63", "Kharkivska oblast"],
  ["UA-65", "Khersonska oblast"],
  ["UA-68", "Khmelnytska oblast"],
  ["UA-35", "Kirovohradska oblast"],
  ["UA-32", "Kyivska oblast"],
  ["UA-09", "Luhanska oblast"],
  ["UA-46", "Lvivska oblast"],
  ["UA-48", "Mykolaivska oblast"],
  ["UA-51", "Odeska oblast"],
  ["UA-53", "Poltavska oblast"],
  ["UA-56", "Rivnenska oblast"],
  ["UA-59", "Sumska oblast"],
  ["UA-61", "Ternopilska oblast"],
  ["UA-05", "Vinnytska oblast"],
  ["UA-07", "Volynska oblast"],
  ["UA-21", "Zakarpatska oblast"],
  ["UA-23", "Zaporizka oblast"],
  ["UA-18", "Zhytomyrska oblast"],
]);

const uaeEmirates = new Map([
  ["AZ", "Abu Dhabi"],
  ["AJ", "Ajman"],
  ["FU", "Fujairah"],
  ["SH", "Sharjah"],
  ["DU", "Dubai"],
  ["RK", "Ras al-Khaimah"],
  ["UQ", "Umm al-Quwain"],
]);

const usaStates = new Map([
  ["AL", "Alabama"],
  ["AK", "Alaska"],
  ["AS", "American Samoa"],
  ["AZ", "Arizona"],
  ["AR", "Arkansas"],
  ["CA", "California"],
  ["CO", "Colorado"],
  ["CT", "Connecticut"],
  ["DE", "Delaware"],
  ["DC", "District Of Columbia"],
  ["FM", "Federated States of Micronesia"],
  ["FL", "Florida"],
  ["GA", "Georgia"],
  ["GU", "Guam"],
  ["HI", "Hawaii"],
  ["ID", "Idaho"],
  ["IL", "Illinois"],
  ["IN", "Indiana"],
  ["IA", "Iowa"],
  ["KS", "Kansas"],
  ["KY", "Kentucky"],
  ["LA", "Louisiana"],
  ["ME", "Maine"],
  ["MH", "Marshall Islands"],
  ["MD", "Maryland"],
  ["MA", "Massachusetts"],
  ["MI", "Michigan"],
  ["MN", "Minnesota"],
  ["MS", "Mississippi"],
  ["MO", "Missouri"],
  ["MT", "Montana"],
  ["NE", "Nebraska"],
  ["NV", "Nevada"],
  ["NH", "New Hampshire"],
  ["NJ", "New Jersey"],
  ["NM", "New Mexico"],
  ["NY", "New York"],
  ["NC", "North Carolina"],
  ["ND", "North Dakota"],
  ["MP", "Northern Mariana Islands"],
  ["OH", "Ohio"],
  ["OK", "Oklahoma"],
  ["OR", "Oregon"],
  ["PW", "Palau"],
  ["PA", "Pennslyvania"],
  ["PR", "Puerto Rico"],
  ["RI", "Rhode Island"],
  ["SC", "South Carolina"],
  ["SD", "South Dakota"],
  ["TN", "Tennessee"],
  ["TX", "Texas"],
  ["UT", "Utah"],
  ["VT", "Vermont"],
  ["VI", "Virgin Islands"],
  ["VA", "Virginia"],
  ["WA", "Washington"],
  ["WV", "West Virginia"],
  ["WI", "Wisconsin"],
  ["WY", "Wyoming"],
]);

const uruguayanDepartments = new Map([
  ["UY-AR", "Artigas"],
  ["UY-CA", "Canelones"],
  ["UY-CL", "Cerro Largo"],
  ["UY-CO", "Colonia"],
  ["UY-DU", "Durazno"],
  ["UY-FS", "Flores"],
  ["UY-FD", "Florida"],
  ["UY-LA", "Lavalleja"],
  ["UY-MA", "Maldonado"],
  ["UY-MO", "Montevideo"],
  ["UY-PA", "Paysandú"],
  ["UY-RV", "Rivera"],
  ["UY-RO", "Rocha"],
  ["UY-RN", "Río Negro"],
  ["UY-SA", "Salto"],
  ["UY-SJ", "San José"],
  ["UY-SO", "Soriano"],
  ["UY-TA", "Tacuarembó"],
  ["UY-TT", "Treinta y Tres"],
]);

const uzbekRegions = new Map([
  ["UZ-AN", "Andijon"],
  ["UZ-BU", "Buxoro"],
  ["UZ-FA", "Farg`ona"],
  ["UZ-JI", "Jizzax"],
  ["UZ-NG", "Namangan"],
  ["UZ-NW", "Navoiy"],
  ["UZ-QA", "Qashqadaryo"],
  ["UZ-SA", "Samarqand"],
  ["UZ-SI", "Sirdaryo"],
  ["UZ-SU", "Surxondaryo"],
  ["UZ-TO", "Toshkent"],
  ["UZ-XO", "Xorazm"],
]);

const venezuelanStates = new Map([
  ["VE-Z", "Amazonas"],
  ["VE-B", "Anzoátegui"],
  ["VE-C", "Apure"],
  ["VE-D", "Aragua"],
  ["VE-E", "Barinas"],
  ["VE-F", "Bolívar"],
  ["VE-G", "Carabobo"],
  ["VE-H", "Cojedes"],
  ["VE-Y", "Delta Amacuro"],
  ["VE-I", "Falcón"],
  ["VE-J", "Guárico"],
  ["VE-X", "La Guaira"],
  ["VE-K", "Lara"],
  ["VE-M", "Miranda"],
  ["VE-N", "Monagas"],
  ["VE-L", "Mérida"],
  ["VE-O", "Nueva Esparta"],
  ["VE-P", "Portuguesa"],
  ["VE-R", "Sucre"],
  ["VE-T", "Trujillo"],
  ["VE-S", "Táchira"],
  ["VE-U", "Yaracuy"],
  ["VE-V", "Zulia"],
]);

const vietnameseProvinces = new Map([
  ["VN-44", "An Giang"],
  ["VN-43", "Bà Rịa - Vũng Tàu"],
  ["VN-57", "Bình Dương"],
  ["VN-58", "Bình Phước"],
  ["VN-40", "Bình Thuận"],
  ["VN-31", "Bình Định"],
  ["VN-55", "Bạc Liêu"],
  ["VN-54", "Bắc Giang"],
  ["VN-53", "Bắc Kạn"],
  ["VN-56", "Bắc Ninh"],
  ["VN-50", "Bến Tre"],
  ["VN-04", "Cao Bằng"],
  ["VN-59", "Cà Mau"],
  ["VN-30", "Gia Lai"],
  ["VN-03", "Hà Giang"],
  ["VN-63", "Hà Nam"],
  ["VN-23", "Hà Tĩnh"],
  ["VN-14", "Hòa Bình"],
  ["VN-66", "Hưng Yên"],
  ["VN-61", "Hải Dương"],
  ["VN-73", "Hậu Giang"],
  ["VN-34", "Khánh Hòa"],
  ["VN-47", "Kiến Giang"],
  ["VN-28", "Kon Tum"],
  ["VN-01", "Lai Châu"],
  ["VN-41", "Long An"],
  ["VN-02", "Lào Cai"],
  ["VN-35", "Lâm Đồng"],
  ["VN-09", "Lạng Sơn"],
  ["VN-67", "Nam Định"],
  ["VN-22", "Nghệ An"],
  ["VN-18", "Ninh Bình"],
  ["VN-36", "Ninh Thuận"],
  ["VN-68", "Phú Thọ"],
  ["VN-32", "Phú Yên"],
  ["VN-24", "Quảng Bình"],
  ["VN-27", "Quảng Nam"],
  ["VN-29", "Quảng Ngãi"],
  ["VN-13", "Quảng Ninh"],
  ["VN-25", "Quảng Trị"],
  ["VN-52", "Sóc Trăng"],
  ["VN-05", "Sơn La"],
  ["VN-21", "Thanh Hóa"],
  ["VN-20", "Thái Bình"],
  ["VN-69", "Thái Nguyên"],
  ["VN-26", "Thừa Thiên-Huế"],
  ["VN-46", "Tiền Giang"],
  ["VN-51", "Trà Vinh"],
  ["VN-07", "Tuyên Quang"],
  ["VN-37", "Tây Ninh"],
  ["VN-49", "Vĩnh Long"],
  ["VN-70", "Vĩnh Phúc"],
  ["VN-06", "Yên Bái"],
  ["VN-71", "Điện Biên"],
  ["VN-33", "Đắk Lắk"],
  ["VN-72", "Đắk Nông"],
  ["VN-39", "Đồng Nai"],
  ["VN-45", "Đồng Tháp"],
]);

const firstAdministrativeLevels = new Map([
  ["AR", argentineProvinces],
  ["AU", australianStates],
  ["AT", austrianStates],
  ["BS", bahamianDistricts],
  ["BB", barbadianParishes],
  ["BY", belarusianOblasts],
  ["BR", brazilianStates],
  ["CA", canadianProvinces],
  ["CV", capeVerdeanMunicipalities],
  ["CL", chileanRegions],
  ["CN", chineseProvinces],
  ["CO", columbianDepartments],
  ["CR", costaRicanProvinces],
  ["EG", egyptianGovernorates],
  ["SV", salvadoranDepartments],
  ["FR", frenchRegions],
  ["DE", germanLands],
  ["GT", guatemalanDepartments],
  ["HN", honduranDepartments],
  ["HK", hongKongRegions],
  ["IN", indianStates],
  ["ID", indonesianProvinces],
  ["IQ", iraqiGovernorates],
  ["IE", irishCounties],
  ["IT", italianProvinces],
  ["JM", jamaicanParishes],
  ["JP", japanesePrefectures],
  ["KZ", kazakhstanRegions],
  ["KI", kiribatianIslands],
  ["MY", malaysianStates],
  ["MX", mexicanStates],
  ["MN", mongolianProvinces],
  ["MZ", mozambicanProvinces],
  ["NR", nauruanDistricts],
  ["NZ", newZealandProvinces],
  ["NI", nicaraguanDepartments],
  ["NG", nigerianStates],
  ["PA", panamanianProvinces],
  ["PG", papaNewGuineanProvinces],
  ["PE", peruvianRegions],
  ["PH", philippineRegions],
  ["PL", polishVoivodships],
  ["PT", portugueseRegions],
  ["RO", romanianCounties],
  ["RU", russianRegions],
  ["KN", saintKittAndNevisParishes],
  ["SO", somalianRegions],
  ["ZA", southAfricanProvinces],
  ["KR", southKoreanProvinces],
  ["ES", spanishProvinces],
  ["SR", surinameseDistricts],
  ["CH", swissCantons],
  ["TH", thaiProvinces],
  ["TR", turkishProvinces],
  ["TV", tuvaluanIslands],
  ["UA", ukrainianRegions],
  ["AE", uaeEmirates],
  ["US", usaStates],
  ["UY", uruguayanDepartments],
  ["UZ", uzbekRegions],
  ["VE", venezuelanStates],
  ["VN", vietnameseProvinces],
]);

const phoneCodes = new Map([
  ["AR", "54"],
  ["AM", "374"],
  ["AU", "61"],
  ["AT", "43"],
  ["BS", "+1-242"],
  ["BB", "+1-246"],
  ["BY", "375"],
  ["BR", "55"],
  ["CA", "1"],
  ["CV", "238"],
  ["CL", "56"],
  ["CN", "86"],
  ["CO", "57"],
  ["CR", "506"],
  ["EG", "20"],
  ["SV", "503"],
  ["FR", "33"],
  ["DE", "49"],
  ["GT", "502"],
  ["HN", "504"],
  ["HK", "852"],
  ["IN", "91"],
  ["ID", "62"],
  ["IQ", "964"],
  ["IE", "353"],
  ["IT", "39"],
  ["JM", "+1-876"],
  ["JP", "81"],
  ["KZ", "7"],
  ["KI", "686"],
  ["MY", "60"],
  ["MX", "52"],
  ["MN", "976"],
  ["MZ", "258"],
  ["NR", "674"],
  ["NZ", "64"],
  ["NI", "505"],
  ["NG", "234"],
  ["PA", "507"],
  ["PG", "675"],
  ["PE", "51"],
  ["PH", "63"],
  ["PL", "48"],
  ["PT", "351"],
  ["RO", "40"],
  ["RU", "7"],
  ["KN", "+1-869"],
  ["SO", "252"],
  ["ZA", "27"],
  ["KR", "82"],
  ["ES", "34"],
  ["SR", "597"],
  ["CH", "41"],
  ["TH", "66"],
  ["TR", "90"],
  ["TV", "688"],
  ["UA", "380"],
  ["AE", "971"],
  ["US", "1"],
  ["UY", "598"],
  ["UZ", "998"],
  ["VE", "58"],
  ["VN", "84"],
]);

function getFullAddressLevel1(country, addressLevel1) {
  return firstAdministrativeLevels.has(country)
    ? firstAdministrativeLevels.get(country).get(addressLevel1)
    : addressLevel1;
}
